### ISSUE TITLE
[QUESTION] Support for multiple groups

### ISSUE THREAD

**Issue by ghost** [volanja/ansible-sample-tdd#6]
I have host file like this:

```
 [group1]
 x.x.x.x
 x.x.x.x

 [group2]
 x.x.x.x
 x.x.x.x

 [group2]
 x.x.x.x
 x.x.x.x

 [group3]
 x.x.x.x
 x.x.x.x

 [group4]
 x.x.x.x
 x.x.x.x
```

And now you only can run tests with all nodes or only with a group with _hosts:_ parameter in playbook.

```
- name: Ansible-Sample-TDD
  hosts: [server/all]
  user: root
  vars:
    worker_connections: 8192
  roles:
    - nginx
    - mariadb
```

Is possible run a test in more than one but not in all groups?
